name: Agent CI

on:
  pull_request:
    branches:
    - develop
    - main

jobs:
  secrets:
    name: Scan secrets
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Scan hardcoded secrets
      uses: secret-scanner/action@0.2.1
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run lint
      uses: docker/build-push-action@v5
      with:
        file: ./Dockerfile.lint
        context: .
        push: false
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run tests
      uses: docker/build-push-action@v5
      with:
        file: ./Dockerfile.test
        outputs: type=local,dest=./artifacts
        context: .
        push: false
    - name: Report
      uses: mikepenz/action-junit-report@v4
      with:
        check_name: Small tests
        report_paths: 'artifacts/results-small.xml'
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build jacktrip-agent
      uses: docker/build-push-action@v5
      with:
        file: ./Dockerfile
        outputs: type=local,dest=./artifacts
        context: .
        push: false
